import Head from "next/head";
import { ReactNode } from "react";
import Navbar from "./Navbar";

type PropsType = {
  children: ReactNode;
};

export default function Layout({ children }: PropsType) {
  return (
    <div>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, inital-scale=1" />
        <link rel="icon" href="../favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </div>
  );
}
